[package]
name = "exex_grpc_node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
eyre.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true

example-exex-remote = {git = "https://github.com/dexloom/reth-exex-grpc"}
#example-exex-remote = {path= "../../../reth-exex-grpc"}

reth.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-tracing.workspace = true

